---
version: '3'
services:
  app:
    build: .
    env_file: ".env"
    command: sh -c "flask run --host ${FLASK_HOST} --port ${FLASK_PORT}"
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./:/usr/src/app
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
